### ISSUE TITLE
new version of TRMM.

### ISSUE THREAD

**Issue by vlouf** [vlouf/matchproj-python#6]
The newest version of TRMM products have changed quite a lot of things, it's now only one file instead of two, and it's in HDF5 instead of HDF. 

Question is, do we keep the compatibility for the old version, or do we  change the code for it to be compatible with the newest version?

**Comment by joshua-wx** [comment]
If there's an improvement in calibration we'll have to change to the new file format and download all the data again :'(

**Comment by vlouf** [comment]
Now the new version handles both the old version and the new version of TRMM data.
